-- docs/migrations/20260722_sam_cali_name_fix.sql
--
-- Replaces abbreviated wrestler names (e.g. "J. Barron") stored in
-- wrestler1_name_raw / wrestler2_name_raw for Sam Cali bouts with the full
-- names derived from the pipe-CSV cross-reference encoded in
-- scripts/import_sam_cali_csv.py _FULL_NAME_LOOKUP.
--
-- 358 distinct (weight, abbreviated_name) pairs resolved.
-- 12 stubs remain unresolved — listed at the bottom of this file.
-- Do NOT apply this migration until you have resolved the stubs or explicitly
-- accepted leaving them abbreviated.
--
-- Tournament: Sam Cali Battle for The Belt
--   in_season_tournament_id: bcfb7e9a-eb02-48c4-9d4a-d7776ec87e56
--
-- APPLY ORDER: after 20260722_patch_sam_cali_school_abbreviations.sql

BEGIN;

WITH name_fixes (wt, abbrev, full_name) AS (
  VALUES
    (106::integer, 'A. Dyki'::text, 'Alexander Dyki'::text),
    (106, 'A. Lopera', 'Anthony Lopera'),
    (106, 'C. Parke', 'Calvin Parke'),
    (106, 'C. Taylor', 'Carson Taylor'),
    (106, 'D. Malfitano', 'Dominick Malfitano'),
    (106, 'E. Shea', 'Eli Shea'),
    (106, 'F. Andersen', 'Finn Andersen'),
    (106, 'H. Karp', 'Hunter Karp'),
    (106, 'J. Appello', 'Jake Appello'),
    (106, 'J. Martin', 'Jordan Martin'),
    (106, 'J. Mazzurco', 'Jake Mazzurco'),
    (106, 'J. Tarantino', 'John Tarantino'),
    (106, 'J. Weber', 'Jaxson Weber'),
    (106, 'L. Bailey', 'Logan Bailey'),
    (106, 'L. Rivara', 'Luke Rivara'),
    (106, 'M. Gaft', 'Maxim Gaft'),
    (106, 'M. Olivieri', 'Mikey Olivieri'),
    (106, 'N. Mateus', 'Nicholas Mateus'),
    (106, 'N. Nguyen', 'Nicholas Nguyen'),
    (106, 'N. Raggazzone', 'Niko Raggazzone'),
    (106, 'R. Rodriguez', 'Ronnie Rodriguez'),
    (106, 'R. Torres', 'Rafael Torres'),
    (106, 'S. Cantarero', 'Sebastian Cantarero'),
    (106, 'S. Hanley', 'Seamus Hanley'),
    (106, 'S. Mazin', 'Sam Mazin'),
    (106, 'S. Vidal', 'Steven Vidal'),
    (106, 'V. Delaney', 'Valen Delaney'),
    (106, 'V. Petriello', 'Vincent Petriello'),
    (106, 'W. Ratz', 'William Ratz'),
    (113, 'A. Camargo', 'Alessandro Camargo'),
    (113, 'A. Meehan', 'Aidan Meehan'),
    (113, 'B. Chacko', 'Ben Chacko'),
    (113, 'B. Ruiz', 'Braedan Ruiz'),
    (113, 'C. Berkowitz', 'Chase Berkowitz'),
    (113, 'C. DePersis', 'Connor DePersis'),
    (113, 'C. Pacor', 'Caleb Pacor'),
    (113, 'C. Powell', 'Christopher Powell'),
    (113, 'D. Bubnowski', 'David Bubnowski'),
    (113, 'D. Coppola', 'Dominic Coppola'),
    (113, 'D. Litterio', 'Dominic Litterio'),
    (113, 'D. Petulla', 'Dominic Petulla'),
    (113, 'D. Sierra', 'Dylan Sierra'),
    (113, 'D. Torsone', 'DJ Torsone'),
    (113, 'J. Cambell', 'Jacob Campbell'),
    (113, 'J. Feliciano', 'Julius Feliciano'),
    (113, 'J. Gallagher', 'Joseph Gallagher'),
    (113, 'M. Barra', 'Marco Barra'),
    (113, 'M. Emmert', 'Maxwell Emmert'),
    (113, 'N. Perez', 'Noah Perez'),
    (113, 'O. Carrillo-Sol…', 'Omar Carrillo-Solano'),
    (113, 'P. Nitche', 'Preston Nitche'),
    (113, 'S. Tracey', 'Shea Tracey'),
    (113, 'T. Connelly', 'Tanner Connelly'),
    (113, 'T. Rosemeyer', 'Tristan Rosemeyer'),
    (113, 'V. Iaquinto', 'Vincent Iaquinto'),
    (113, 'Z. Shama', 'Zane Shama'),
    (120, 'A. Matias', 'Aidan Matias'),
    (120, 'A. Murado', 'Alec Murado'),
    (120, 'B. Banks', 'Benjamin Banks'),
    (120, 'B. Cole', 'Benjamin Cole'),
    (120, 'B. Jarosz', 'Bryson Jarosz'),
    (120, 'C. Kastner', 'Chase Kastner'),
    (120, 'C. Sampedro', 'Camilo Sampedro'),
    (120, 'D. DeLuca', 'Demitri DeLuca'),
    (120, 'D. Montalvan', 'Dan Montalvan'),
    (120, 'D. Vazquez', 'David Vazquez'),
    (120, 'E. Blanchard', 'Evan Blanchard'),
    (120, 'G. Stempkow…', 'Gavin Stempkowski'),
    (120, 'J. Barron', 'John Barron'),
    (120, 'J. Ciullo', 'Joseph Ciullo'),
    (120, 'J. Finkelstein', 'Jack Finkelstein'),
    (120, 'J. Leneus', 'Jayden Leneus'),
    (120, 'J. Polanco', 'Julian Polanco'),
    (120, 'J. Rowinski', 'Joseph Rowinski'),
    (120, 'L. Pelc', 'Lucas Pelc'),
    (120, 'L. Perez', 'Lucas Perez'),
    (120, 'L. Perillo', 'Luca Perillo'),
    (120, 'M. Abuhadba', 'Muhammad Abuhadba'),
    (120, 'M. Daly', 'Michael Daly'),
    (120, 'M. Romero', 'Mason Romero'),
    (120, 'M. Torres', 'Morgan Torres'),
    (120, 'N. Gallo', 'Nicholas Gallo'),
    (120, 'N. Hernandez', 'Noah Hernandez'),
    (120, 'P. Trezza', 'Peter Trezza'),
    (120, 'R. Lightfoot', 'Reid Lightfoot'),
    (120, 'R. Rodriguez', 'Robert Rodriguez'),
    (120, 'S. Malfitano', 'Steven Malfitano'),
    (126, 'A. Martin', 'Andre Martin'),
    (126, 'B. Housel', 'Braydon Housel'),
    (126, 'C. Coreggio', 'Cassen Correggio'),
    (126, 'C. Klein', 'Connor Klein'),
    (126, 'C. Severs', 'Chace Severs'),
    (126, 'C. Sontz', 'Cameron Sontz'),
    (126, 'D. Rosen', 'Dan Rosen'),
    (126, 'G. Gutierrez', 'Giovanni Gutierrez'),
    (126, 'J. Bucco', 'Jax Bucco'),
    (126, 'J. Cruz', 'Jayden Cruz'),
    (126, 'J. Pellicci', 'Joseph Pellicci'),
    (126, 'J. Richardson', 'Jacob Richardson'),
    (126, 'J. Sulca', 'Jaydon Sulca'),
    (126, 'J. Viola', 'Joseph Viola'),
    (126, 'K. Battulga', 'Khuchuleg Battulga'),
    (126, 'L. Churpakovi…', 'Lucas Churpakovich'),
    (126, 'M. Droz', 'Mariano Droz'),
    (126, 'M. Echeverri', 'Michael Echeverri'),
    (126, 'M. Graeber', 'Max Graeber'),
    (126, 'M. Kleynshvag', 'Michael Kleynshvag'),
    (126, 'R. Horner', 'Ryan Horner'),
    (126, 'R. Hubert', 'Rohi Hubert'),
    (126, 'R. Spinelli', 'Ryan Spinelli'),
    (126, 'V. DeSomma', 'Vincent DeSomma'),
    (132, 'A. Cedeno', 'Adan Cedeno'),
    (132, 'A. Morero', 'Andre Morero'),
    (132, 'A. Spina', 'Antonio Spina'),
    (132, 'A. Stover', 'Anthony Stover'),
    (132, 'C. DeAngelo', 'Cole DeAngelo'),
    (132, 'C. Glory', 'Connor Glory'),
    (132, 'D. Butenewicz', 'David Butenewicz'),
    (132, 'D. Kelly', 'Dontae Kelly'),
    (132, 'D. Weber', 'Dalton Weber'),
    (132, 'J. Corelli', 'Jack Corelli'),
    (132, 'J. Francis', 'Jack Francis'),
    (132, 'J. Monto', 'Joseph Monto'),
    (132, 'J. Rizzuto', 'Joseph Rizzuto'),
    (132, 'M. Oliveri', 'Michael Oliveri'),
    (132, 'M. Velez', 'Mathew Velez Intriago'),
    (132, 'N. Marchetti', 'Nicholas Marchetti'),
    (132, 'P. Terranova', 'Peter Terranova'),
    (132, 'R. DeLorenzo II', 'Richard DeLorenzo II'),
    (132, 'R. Dyki', 'Ryan Dyki'),
    (132, 'R. Fontanelli', 'Rocco Fontanelli'),
    (132, 'R. Hibler', 'River Hibler'),
    (132, 'R. Mohammed', 'Rayan Mohammad'),
    (138, 'A. Vann', 'Amari Vann'),
    (138, 'A. Zelna', 'Alex Zelna'),
    (138, 'B. Dougherty', 'Bryan Dougherty'),
    (138, 'C. Cifelli', 'Christopher Cifelli'),
    (138, 'C. Hansen', 'Chase Hansen'),
    (138, 'C. Kelesidis', 'Chris Kelesidis'),
    (138, 'D. Sawyer', 'David Sawyer'),
    (138, 'D. cerciello', 'Dylan Cerciello'),
    (138, 'I. Hernandez', 'Isaias Hernandez'),
    (138, 'J. Abramson', 'Jack Abramson'),
    (138, 'J. Puleo', 'Jared Puleo'),
    (138, 'L. Lill', 'Landon Lill'),
    (138, 'L. Rafeh', 'Lucas Rafeh'),
    (138, 'L. Williams', 'Liam Williams'),
    (138, 'M. Abuharthieh', 'Malik Abuharthieh'),
    (138, 'M. Miller', 'Matthew Miller'),
    (138, 'N. Kadar', 'Nathan Kadar'),
    (138, 'N. Marchetti', 'Nicholas Marchetti'),
    (138, 'N. Pugliese', 'Nicky Pugliese'),
    (138, 'R. Douangmala', 'Robert Douangmala'),
    (138, 'R. Douangma…', 'Robert Douangmala'),
    (138, 'R. KOZUBAL', 'Rhys Kozubal'),
    (138, 'R. connors', 'Ryder Connors'),
    (138, 'S. Brown', 'Sean Brown'),
    (144, 'A. Dispensa', 'Anthony Dispensa'),
    (144, 'A. Matter', 'Andrew Matter'),
    (144, 'A. Pinto', 'Adrian Pinto'),
    (144, 'B. Ingram', 'Bradley Ingram'),
    (144, 'B. Karvoski', 'Brighton Karvoski'),
    (144, 'B. Katimbang', 'Brendon Katimbang'),
    (144, 'C. Anzaldo', 'CJ Anzaldo'),
    (144, 'D. Biegel', 'Dylan Biegel'),
    (144, 'D. Marrero', 'Dominick Marrero'),
    (144, 'D. Rodriguez', 'Darryen Rodriguez'),
    (144, 'D. Rotte', 'Delvan Rotte'),
    (144, 'E. Delacruz', 'Ethan Delacruz'),
    (144, 'E. Perez', 'Ethan Perez'),
    (144, 'I. Konstantini…', 'Ilias Konstantinidis'),
    (144, 'J. Owen', 'John Owen'),
    (144, 'L. Ramos', 'Luken Ramos'),
    (144, 'M. Ventura', 'Max Ventura'),
    (144, 'N. Emmert', 'Nathan Emmert'),
    (144, 'N. Pallitto', 'Nicholas Pallitto'),
    (144, 'S. Morris', 'Sean Morris'),
    (144, 'X. Gonzalez', 'Xavier Gonzalez'),
    (150, 'A. Brant', 'Andrew Brant'),
    (150, 'A. Bray', 'Anthony Bray'),
    (150, 'A. Liss', 'Alexander Liss'),
    (150, 'A. Russo', 'Anthony Russo'),
    (150, 'B. Meserlian', 'Bryce Meserlian'),
    (150, 'B. Tiernan', 'Brady Tiernan'),
    (150, 'C. Jung', 'Christian Jung'),
    (150, 'D. Arroyo', 'Daniel Arroyo'),
    (150, 'D. Grayson', 'Devin Grayson'),
    (150, 'D. Raveis', 'Dane Raveis'),
    (150, 'D. VonderLind…', 'Damian Vonderlinden'),
    (150, 'E. Triola', 'Enzo Triola'),
    (150, 'I. Vuka', 'Ilirian Vuka'),
    (150, 'J. Mahoney', 'Joseph Mahoney'),
    (150, 'J. Riccio', 'Joseph Riccio'),
    (150, 'J. Walker', 'Jacob Walker'),
    (150, 'K. Sheridan', 'Kane Sheridan'),
    (150, 'L. Riker', 'Luke Riker'),
    (150, 'L. Valentin', 'Lukas Valentin'),
    (150, 'L. Zimmer', 'Logan Zimmer'),
    (150, 'M. Boulard', 'Michael Boulard'),
    (150, 'M. Pocius', 'Michael Pocius'),
    (150, 'N. Barone', 'Nicholas Barone'),
    (150, 'O. Gluckow', 'Oskar Gluckow'),
    (150, 'T. Grageda', 'Trevor Grageda'),
    (150, 'T. King', 'Tyler King'),
    (150, 'V. Castrofilip…', 'Vin Castrofilippo'),
    (150, 'W. Clasen', 'William Clasen'),
    (157, 'C. Hoffman', 'Cael Hoffman'),
    (157, 'C. Jasinkiewicz', 'Cole Jasinkiewicz'),
    (157, 'C. Smyth', 'Colin Smyth'),
    (157, 'D. Byrne', 'Daniel Byrne'),
    (157, 'D. LiSanti', 'Dominic Lisanti'),
    (157, 'E. Hufnagel', 'Eddie Hufnagel'),
    (157, 'F. Monto', 'Frank Monto'),
    (157, 'H. Asatrian.Jr', 'Harry Asatrian'),
    (157, 'J. Devlin', 'Jamison Devlin'),
    (157, 'J. Jones', 'Jacob Jones'),
    (157, 'J. Marsella', 'Jeremy Marsella'),
    (157, 'J. McGrath', 'Jeremy McGrath'),
    (157, 'J. Ruiz', 'Joseph Ruiz'),
    (157, 'L. Meisenhol…', 'Lucas Meisenholder'),
    (157, 'L. Scholz', 'Luke Scholz'),
    (157, 'L. Stempkows…', 'Luke Stempkowski'),
    (157, 'M. Summa', 'Matt Summa'),
    (157, 'M. Tafida', 'Muhammed Tafida'),
    (157, 'O. Miller', 'Owen Miller'),
    (157, 'P. Quinn', 'Parker Quinn'),
    (157, 'R. Ritacco', 'Roman Ritacco'),
    (157, 'S. Love', 'Sean Love'),
    (157, 'T. Burke', 'Thomas Burke'),
    (157, 'T. Morodan', 'Tyler Morodan'),
    (157, 'T. Tracey', 'Torrin Tracey'),
    (157, 'T. Whartnaby', 'Tyler Whartnaby'),
    (165, 'A. DeLorenzo', 'Anthony DeLorenzo'),
    (165, 'A. Rotbaum', 'Aidan Rotbaum'),
    (165, 'B. Causillas', 'Branden Causillas'),
    (165, 'B. Watkins', 'Blake Watkins'),
    (165, 'C. Ferranti', 'Chris Ferranti'),
    (165, 'C. Pote', 'Cameron Pote'),
    (165, 'C. Rodriguez', 'Cristian Rodriguez'),
    (165, 'C. Vital', 'Colby Vital'),
    (165, 'D. Kyzima', 'Daniel Kyzima'),
    (165, 'D. Lopes', 'David Lopes'),
    (165, 'F. Mckeon', 'Finn McKeon'),
    (165, 'G. Giordano', 'Giammaria Giordano'),
    (165, 'J. Acinapura', 'Jared Acinapura'),
    (165, 'J. Aiello', 'Joseph Aiello'),
    (165, 'J. Soy', 'Jayden Soy'),
    (165, 'K. Montoya', 'Kaden Montoya'),
    (165, 'L. Dellavolpe', 'Louis DellaVolpe'),
    (165, 'L. Dimitrakiou', 'Leo Dimitrakiou'),
    (165, 'L. Katsigiannis', 'Lukas Katsigiannis'),
    (165, 'L. Pelletier', 'Lucas Pelletier'),
    (165, 'L. Schulmann', 'Levi Schulmann'),
    (165, 'M. McCann', 'Matthew McCann'),
    (165, 'M. Tripoli', 'Max Tripoli'),
    (165, 'N. Konopka', 'Nicholas Konepka'),
    (165, 'R. Attenboro…', 'Robert Attenborough'),
    (165, 'R. Willi', 'Ryan Willi'),
    (165, 'S. Coppolo', 'Scott Coppolo'),
    (165, 'S. Mello', 'Sincere Mello'),
    (165, 'T. McNamara', 'Timothy McNamara'),
    (165, 'W. Tarna', 'Will Tarna'),
    (175, 'A. Helphingsti…', 'Alex Helphingstine'),
    (175, 'A. Maiden', 'Antonio Maiden'),
    (175, 'B. Papa', 'Brandon Papa'),
    (175, 'C. Dunham', 'Cole Dunham'),
    (175, 'F. Cavanaugh', 'Finn Cavanaugh'),
    (175, 'F. Cespedes', 'Farel Cespedes'),
    (175, 'I. Rojas', 'Isaiah Rojas'),
    (175, 'J. Acinapura', 'Joey Acinapura'),
    (175, 'J. Bullock', 'Justin Bullock'),
    (175, 'J. Harty', 'Jack Harty'),
    (175, 'J. Leiman', 'Jack Leiman'),
    (175, 'K. Morgan', 'Kwabena Morgan'),
    (175, 'L. Hackney', 'Landon Hackney'),
    (175, 'L. Rickard', 'Logan Rickard'),
    (175, 'L. Shivas', 'Luke Shivas'),
    (175, 'L. Van Veen', 'Lukas Van Veen'),
    (175, 'M. Cmielewski', 'Matt Cmielewski'),
    (175, 'N. Nagle', 'Noah Nagle'),
    (175, 'P. Ezeanii', 'Prince Ezenanii'),
    (175, 'R. Bernholz', 'Ryder Bernholz'),
    (175, 'R. Engle', 'Ryan Engle'),
    (175, 'S. Goins', 'Sebastian Goins'),
    (175, 'S. Morrell', 'Shane Morrell'),
    (175, 'S. Rodriguez', 'Santino Rodriguez'),
    (175, 'T. Dochnal', 'Tim Dochnal'),
    (175, 'W. Capizzi', 'William Capizzi'),
    (175, 'X. Torres', 'Xzavier Torres'),
    (175, 'Z. Lombreglia', 'Zach Lombreglia'),
    (190, 'A. Bainbridge', 'Alex Bainbridge'),
    (190, 'A. Cianfrocca', 'Anthony Cianfrocca'),
    (190, 'A. Kirgezmis', 'Artun Kirgezmis'),
    (190, 'A. Wagner', 'Anthony Wagner'),
    (190, 'D. Douglass', 'David Douglass'),
    (190, 'D. Shiroff', 'Dane Shiroff'),
    (190, 'D. Thomson', 'David Thomson'),
    (190, 'G. Oelsner', 'Guy Oelsner'),
    (190, 'G. Sawyer', 'Greg Sawyer'),
    (190, 'H. Rodriguez', 'Hector Rodriguez'),
    (190, 'J. Cutruzzula', 'Joe Cutruzzula'),
    (190, 'J. Sammarta…', 'John Sammartano'),
    (190, 'K. Rafferty', 'Kevin Rafferty'),
    (190, 'L. Fitzsimmons', 'Landon Fitzsimmons'),
    (190, 'L. Lewis', 'Lemuel Lewis'),
    (190, 'M. Brown-Cab…', 'Marlowe Brown-Cabarris'),
    (190, 'M. Damerjian', 'Michael Damerjian'),
    (190, 'M. Morelli', 'Michael Morelli'),
    (190, 'M. Sutton', 'Matthew Sutton'),
    (190, 'N. Mattessich', 'Nevin Mattessich'),
    (190, 'R. Penny', 'Rocky Penny'),
    (190, 'T. Neiva', 'Tyler Neiva'),
    (215, 'A. Arguello', 'Ashton Arguello'),
    (215, 'A. Cassidy', 'August Cassidy'),
    (215, 'A. Cosar', 'Atkan Cosar'),
    (215, 'A. Hidalgo', 'Aren Hidalgo'),
    (215, 'B. Ismael', 'Brody Ismael'),
    (215, 'C. Bonita', 'Carlito Bonita'),
    (215, 'C. Britton', 'Caden Britton'),
    (215, 'C. Diaz', 'Christopher Diaz'),
    (215, 'D. Oxmann', 'Delvin Oxmann'),
    (215, 'G. Abbruzzese', 'Grayson Abbruzzese'),
    (215, 'H. woolley', 'Hayden Woolley'),
    (215, 'J. Barrera', 'Josiah Barrera'),
    (215, 'L. Hassloch', 'Liam Hassloch'),
    (215, 'M. Morrissey', 'Matthew Morrissey'),
    (215, 'N. Fabunan', 'Nate Fabunan'),
    (215, 'N. Gonzalez', 'Nicolas Gonzalez'),
    (215, 'R. Burke', 'Ryan Burke'),
    (215, 'T. Bayarkhuu', 'Tuguldur Bayarkhuu'),
    (215, 'T. Levash', 'Trent Levash'),
    (215, 'T. Skversky', 'Theodore Skversky'),
    (215, 'W. Sisco', 'Wyatt Sisco'),
    (215, 'Z. Ventola', 'Zachary Ventola'),
    (285, 'A. Alfonso', 'Anthony Alfonso'),
    (285, 'A. Evaristo', 'Anthony Evaristo'),
    (285, 'A. Fox', 'Ayden Fox'),
    (285, 'A. Hooey', 'Austin Hooey'),
    (285, 'A. Moser', 'August Moser'),
    (285, 'D. Black', 'Donavan Black'),
    (285, 'D. Infantes', 'Domenick Infantes'),
    (285, 'E. Clauburg', 'Eric Clauburg'),
    (285, 'G. Gomez', 'Gabriel Gomez'),
    (285, 'G. Medina', 'Gabriel Medina-Coello'),
    (285, 'J. Hearon IV', 'John Hearon'),
    (285, 'J. Martini', 'Jared Martini'),
    (285, 'L. Palescando…', 'Lorenzo Palescandolo'),
    (285, 'M. Georges', 'Max Georges'),
    (285, 'M. Oakes', 'Michael Oakes'),
    (285, 'M. Targali', 'Mohammad Targali'),
    (285, 'N. Brewer', 'Nolan Brewer'),
    (285, 'N. Duarte', 'Nicholas Duarte'),
    (285, 'N. McCrone', 'Nathaniel McCrone'),
    (285, 'P. Bertole', 'Philip Bertole'),
    (285, 'R. Schnieder', 'Ryan Schneider'),
    (285, 'S. Brown', 'Sean Brown'),
    (285, 'S. Jean Marie', 'Samuel Jean Marie'),
    (285, 'V. Williams', 'Vincent Williams')
)
UPDATE tournament_bouts tb
SET
  wrestler1_name_raw = COALESCE(
    (SELECT full_name FROM name_fixes
     WHERE wt = tb.weight_class AND abbrev = tb.wrestler1_name_raw),
    tb.wrestler1_name_raw
  ),
  wrestler2_name_raw = COALESCE(
    (SELECT full_name FROM name_fixes
     WHERE wt = tb.weight_class AND abbrev = tb.wrestler2_name_raw),
    tb.wrestler2_name_raw
  )
WHERE tb.in_season_tournament_id = 'bcfb7e9a-eb02-48c4-9d4a-d7776ec87e56'
  AND (
    EXISTS (
      SELECT 1 FROM name_fixes
      WHERE wt = tb.weight_class AND abbrev = tb.wrestler1_name_raw
    )
    OR EXISTS (
      SELECT 1 FROM name_fixes
      WHERE wt = tb.weight_class AND abbrev = tb.wrestler2_name_raw
    )
  );

COMMIT;

-- ── UNRESOLVED STUBS ──────────────────────────────────────────────────────────
-- The following 12 abbreviated names were NOT resolvable from the pipe CSV.
-- They remain as "F. Lastname" stubs in the DB after this migration runs.
-- Each needs a manual answer before a follow-up patch can be written.
--
--  Weight  Abbrev             School (abbrev)  Issue
--  ------  -----------------  ---------------  ---------------------------------
--   106lb  J. Barron          SPP              Not in pipe CSV — first name unknown
--   106lb  J. Rowinski        HTWN             Not in pipe CSV — first name unknown
--   113lb  D. Adell           B-R              Pipe has "Andrew Adell" — is D a typo/OCR error for A?
--   113lb  D. D'Arcy          SBP              Not in pipe CSV — first name unknown
--   120lb  J. Sgrulletta      GFA (OOS)        OOS school; first name unknown
--   126lb  C. O'Connor        DPLC (sch. 22)   Not in pipe CSV — first name unknown
--   126lb  N. O'Sullivan      CHAM (OOS)       OOS school; first name unknown
--   126lb  O. O'Leary         RHS (sch. 156)   Not in pipe CSV — first name unknown
--   126lb  S. D'Arco          PJ23 (sch. 117)  Not in pipe CSV — first name unknown
--   132lb  K. Landell         CHER (sch. 266)  Pipe has "Trenton Landell" — is K a typo/OCR error for T?
--   165lb  T. O'Connor        MTWN (sch. 261)  Not in pipe CSV — first name unknown
--   190lb  B. Washington      DEMA (sch. 314)  Pipe has "Navell Washington" — is B a typo/OCR error for N?

