'use client'

import { useState, useEffect, useCallback, useRef } from 'react'
import Link from 'next/link'
import Image from 'next/image'

// Sprite: 10 cols × 10 rows grid, 600×600 px per cell → 6000×6000 px AVIF canvas.
// 96 frames fill 96 of 100 cells; 4 trailing cells are transparent.
// Display container: 400×400 CSS px; background-size 4000×4000 (0.667× scale).
// Per-frame offset: -col × 400 px left, -row × 400 px top.
//
// Frame rate matches original: steps(33) over 4 s → ~118 ms/frame.
// 96 frames × 118 ms ≈ 11.3 s total (up from 4 s for 34 frames).
//
// AVIF detection: Image() probe against a 1×1 AVIF data URI — tests decode
// support directly, unlike canvas.toDataURL which misses Firefox AVIF decode.
// Non-supporting browsers fall back to static logo + immediate button reveal.
//
// Contrast ratios (WCAG 2.1 relative luminance formula):
//   Boys button:  white (#fff) on black (#000) → 21:1  (exceeds AAA)
//   Girls button: black (#000) on white (#fff) → 21:1  (exceeds AAA)
//
// Colorblind safety: buttons differ by LABEL ("Boys" / "Girls") AND SHAPE
//   (Boys = solid rectangle, Girls = outlined pill). Color is not the only cue.
//
// Button reveal uses opacity (not conditional rendering) so the button row's
// layout space is pre-allocated, preventing CLS when the hero is viewport-sized.

const DISPLAY_PX        = 400
const FRAMES            = 96
const COLS              = 10
const ROWS              = Math.ceil(FRAMES / COLS)   // 10
const FRAME_INTERVAL_MS = Math.round(4000 / 34)      // 118 ms → ~11.3 s total

// 1×1 AVIF generated by sharp/libaom — guaranteed decodable, used to probe browser support
const AVIF_PROBE = 'data:image/avif;base64,AAAAHGZ0eXBhdmlmAAAAAG1pZjFhdmlmbWlhZgAAANZtZXRhAAAAAAAAACFoZGxyAAAAAAAAAABwaWN0AAAAAAAAAAAAAAAAAAAAAA5waXRtAAAAAAABAAAAImlsb2MAAAAAREAAAQABAAAAAAD6AAEAAAAAAAAAFwAAACNpaW5mAAAAAAABAAAAFWluZmUCAAAAAAEAAGF2MDEAAAAAVmlwcnAAAAA4aXBjbwAAAAxhdjFDgSACAAAAABRpc3BlAAAAAAAAAAEAAAABAAAAEHBpeGkAAAAAAwgICAAAABZpcG1hAAAAAAAAAAEAAQOBAgMAAAAfbWRhdBIACgc4AAYQENBpMgoYAAAAQAX172To'

export function FlipbookHero() {
  const [done,          setDone]          = useState(false)
  const [reducedMotion, setReducedMotion] = useState(false)
  const [avifSupported, setAvifSupported] = useState(false)
  const spriteRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const mq = window.matchMedia('(prefers-reduced-motion: reduce)')
    if (mq.matches) {
      setReducedMotion(true)
      setDone(true)
      return
    }

    // Image() probe: the only method that correctly detects AVIF decode support
    // in Firefox (canvas.toDataURL('image/avif') returns PNG in Firefox even
    // when AVIF display is supported).
    let cancelled = false
    const img = new window.Image()
    img.onload = () => {
      if (cancelled) return
      if (img.width > 0) {
        setAvifSupported(true)
      } else {
        setDone(true)
      }
    }
    img.onerror = () => {
      if (!cancelled) setDone(true)
    }
    img.src = AVIF_PROBE
    return () => { cancelled = true }
  }, [])

  const handleAnimationEnd = useCallback(() => setDone(true), [])

  // JS frame ticker — drives background-position directly on each interval tick.
  // CSS steps() can't cleanly animate both axes for a grid whose frame count
  // (96) is not a multiple of COLS (10): the last row has only 6 frames.
  useEffect(() => {
    if (reducedMotion || !avifSupported) return

    let frame = 0
    const id = setInterval(() => {
      frame++
      if (frame >= FRAMES) {
        clearInterval(id)
        handleAnimationEnd()
        return
      }
      const col = frame % COLS
      const row = Math.floor(frame / COLS)
      const el = spriteRef.current
      if (el) {
        el.style.backgroundPositionX = `-${col * DISPLAY_PX}px`
        el.style.backgroundPositionY = `-${row * DISPLAY_PX}px`
      }
    }, FRAME_INTERVAL_MS)

    return () => clearInterval(id)
  }, [reducedMotion, avifSupported, handleAnimationEnd])

  // No-AVIF path mirrors reduced-motion: static logo, buttons immediately visible.
  const showStatic = reducedMotion || !avifSupported

  return (
    <section
      className="flex flex-col items-center"
      aria-label="MatWhizzer hero"
    >
      {/* ── Rise keyframe for button reveal ───────────────────────────────── */}
      <style>{`
        @keyframes mw-rise {
          from { opacity: 0; transform: translateY(10px); }
          to   { opacity: 1; transform: translateY(0); }
        }
      `}</style>

      {/* ── Graphic ────────────────────────────────────────────────────────── */}
      {showStatic ? (
        /* Static path: reduced-motion OR no AVIF support */
        <Image
          src="/logo-final.webp"
          alt="MatWhizzer mascot logo"
          width={DISPLAY_PX}
          height={DISPLAY_PX}
          priority
        />
      ) : (
        <div
          ref={spriteRef}
          role="img"
          aria-label="MatWhizzer mascot logo animation"
          style={{
            width:              DISPLAY_PX,
            height:             DISPLAY_PX,
            backgroundImage:    'url(/flipbook.avif)',
            backgroundRepeat:   'no-repeat',
            backgroundSize:     `${COLS * DISPLAY_PX}px ${ROWS * DISPLAY_PX}px`,
            backgroundPosition: '0 0',
            flexShrink:         0,
          }}
        />
      )}

      {/* ── Entry buttons ──────────────────────────────────────────────────── */}
      {/*
       * Pre-allocated height (opacity, not conditional) prevents CLS:
       * the button row occupies layout space from the start; only its
       * visibility changes when done flips true.
       *
       * Rise animation fires only after the AVIF flipbook completes.
       * Static paths (reduced-motion, no AVIF) skip the rise — buttons
       * appear immediately without animation, matching reduced-motion intent.
       */}
      <div
        className="flex gap-5 mt-8"
        style={{
          opacity:       done ? undefined : 0,
          pointerEvents: done ? 'auto' : 'none',
          animation:     (done && !showStatic) ? 'mw-rise 0.3s ease-out forwards' : undefined,
        }}
      >
        {/*
         * Boys button — solid black rectangle
         * Contrast: white (#fff) on black (#000) = 21:1  ✓ WCAG AAA
         * Shape cue: sharp corners (rounded-none)
         */}
        <Link
          href="/boys"
          className={[
            'flex items-center justify-center gap-2',
            'w-36 py-3',
            'bg-black text-white font-bold text-lg',
            'border-2 border-black',
            'rounded-none',
            'hover:bg-slate-800 hover:border-slate-800',
            'transition-colors',
            'focus:outline-none focus-visible:ring-2 focus-visible:ring-black focus-visible:ring-offset-2',
          ].join(' ')}
        >
          Boys
          <span aria-hidden="true">→</span>
        </Link>

        {/*
         * Girls button — outlined pill
         * Contrast: black (#000) on white (#fff) = 21:1  ✓ WCAG AAA
         * Shape cue: fully rounded (pill) + border-only style
         */}
        <Link
          href="/girls"
          className={[
            'flex items-center justify-center gap-2',
            'w-36 py-3',
            'bg-white text-black font-bold text-lg',
            'border-2 border-black',
            'rounded-full',
            'hover:bg-slate-100',
            'transition-colors',
            'focus:outline-none focus-visible:ring-2 focus-visible:ring-black focus-visible:ring-offset-2',
          ].join(' ')}
        >
          Girls
          <span aria-hidden="true">→</span>
        </Link>
      </div>
    </section>
  )
}
