'use client'

import { useState, useEffect, useCallback } from 'react'
import Link from 'next/link'
import Image from 'next/image'

// Sprite: 10 cols × 10 rows grid, 600×600 px per cell → 6000×6000 px AVIF canvas.
// 96 real frames + 4 padding copies of 97.png fill all 100 cells.
// Display container: 400×400 CSS px; background-size 4000×4000 (0.667× scale).
//
// CSS animation: two compositor-friendly steps() animations, one per axis.
//   X (mw-flipbook-x): steps(10), 400 ms/cycle × 10 cycles = 4 000 ms total
//   Y (mw-flipbook-y): steps(10), 4 000 ms × 1 iteration  = 4 000 ms total
// Y advances exactly once per X cycle, keeping both axes in phase.
// animationend on mw-flipbook-y triggers button reveal; the element is then
// replaced by logo-final.webp (same 97.png image) to cleanly exit fill:forwards.
//
// AVIF detection: Image() probe against a 1×1 AVIF data URI — tests decode
// support directly, unlike canvas.toDataURL which misses Firefox AVIF decode.
// Non-supporting browsers fall back to static logo + immediate button reveal.
//
// Contrast ratios (WCAG 2.1 relative luminance formula):
//   Boys button:  white (#fff) on blue-600 (#2563eb) → 4.6:1  (exceeds AA)
//   Girls button: white (#fff) on rose-800 (#9f1239) → 6.3:1  (exceeds AA)
//
// Colorblind safety: buttons differ by LABEL ("Boys" / "Girls") AND COLOR.
// Both are the same rectangular shape (rounded-none).
//
// Button reveal uses opacity (not conditional rendering) so the button row's
// layout space is pre-allocated, preventing CLS when the hero is viewport-sized.

const DISPLAY_PX = 400
const COLS       = 10
const FRAME_MS   = 10                         // ms per frame (100 fps)
const X_DUR_MS   = FRAME_MS * COLS            // 400 ms per column cycle
const Y_DUR_MS   = FRAME_MS * COLS * COLS     // 4 000 ms total

// 1×1 AVIF generated by sharp/libaom — guaranteed decodable, used to probe browser support
const AVIF_PROBE = 'data:image/avif;base64,AAAAHGZ0eXBhdmlmAAAAAG1pZjFhdmlmbWlhZgAAANZtZXRhAAAAAAAAACFoZGxyAAAAAAAAAABwaWN0AAAAAAAAAAAAAAAAAAAAAA5waXRtAAAAAAABAAAAImlsb2MAAAAAREAAAQABAAAAAAD6AAEAAAAAAAAAFwAAACNpaW5mAAAAAAABAAAAFWluZmUCAAAAAAEAAGF2MDEAAAAAVmlwcnAAAAA4aXBjbwAAAAxhdjFDgSACAAAAABRpc3BlAAAAAAAAAAEAAAABAAAAEHBpeGkAAAAAAwgICAAAABZpcG1hAAAAAAAAAAEAAQOBAgMAAAAfbWRhdBIACgc4AAYQENBpMgoYAAAAQAX172To'

export function FlipbookHero() {
  const [done,          setDone]          = useState(false)
  const [reducedMotion, setReducedMotion] = useState(false)
  const [avifSupported, setAvifSupported] = useState(false)

  useEffect(() => {
    const mq = window.matchMedia('(prefers-reduced-motion: reduce)')
    if (mq.matches) {
      setReducedMotion(true)
      setDone(true)
      return
    }

    // Image() probe: the only method that correctly detects AVIF decode support
    // in Firefox (canvas.toDataURL('image/avif') returns PNG in Firefox even
    // when AVIF display is supported).
    let cancelled = false
    const img = new window.Image()
    img.onload = () => {
      if (cancelled) return
      if (img.width > 0) {
        setAvifSupported(true)
      } else {
        setDone(true)
      }
    }
    img.onerror = () => {
      if (!cancelled) setDone(true)
    }
    img.src = AVIF_PROBE
    return () => { cancelled = true }
  }, [])

  // Fires when the Y animation ends (4 000 ms).  X also dispatches animationend
  // on the same element; filtering by name prevents a double setDone call.
  const handleAnimationEnd = useCallback((e: React.AnimationEvent<HTMLDivElement>) => {
    if (e.animationName === 'mw-flipbook-y') setDone(true)
  }, [])

  // No-AVIF path mirrors reduced-motion: static logo, buttons immediately visible.
  const showStatic = reducedMotion || !avifSupported

  return (
    <section
      className="flex flex-col items-center"
      aria-label="MatWhizzer hero"
    >
      {/* ── Keyframes ─────────────────────────────────────────────────────── */}
      <style>{`
        @keyframes mw-flipbook-x {
          from { background-position-x: 0; }
          to   { background-position-x: -${COLS * DISPLAY_PX}px; }
        }
        @keyframes mw-flipbook-y {
          from { background-position-y: 0; }
          to   { background-position-y: -${COLS * DISPLAY_PX}px; }
        }
        @keyframes mw-rise {
          from { opacity: 0; transform: translateY(10px); }
          to   { opacity: 1; transform: translateY(0); }
        }
      `}</style>

      {/* ── Graphic ────────────────────────────────────────────────────────── */}
      {/*
       * Static path (reduced-motion, no AVIF) AND post-animation:
       * show logo-final.webp.  Replacing the sprite div on done=true cleanly
       * exits animation-fill-mode:forwards before the browser can paint the
       * mathematical end value (-4000px × -4000px = transparent cell 10,10).
       */}
      {(showStatic || done) ? (
        <Image
          src="/logo-final.webp"
          alt="MatWhizzer mascot logo"
          width={DISPLAY_PX}
          height={DISPLAY_PX}
          priority
        />
      ) : (
        <div
          role="img"
          aria-label="MatWhizzer mascot logo animation"
          onAnimationEnd={handleAnimationEnd}
          style={{
            width:                   DISPLAY_PX,
            height:                  DISPLAY_PX,
            backgroundImage:         'url(/flipbook.avif)',
            backgroundRepeat:        'no-repeat',
            backgroundSize:          `${COLS * DISPLAY_PX}px ${COLS * DISPLAY_PX}px`,
            backgroundPosition:      '0 0',
            flexShrink:              0,
            animationName:           'mw-flipbook-x, mw-flipbook-y',
            animationDuration:       `${X_DUR_MS}ms, ${Y_DUR_MS}ms`,
            animationTimingFunction: `steps(${COLS}), steps(${COLS})`,
            animationIterationCount: `${COLS}, 1`,
            animationFillMode:       'forwards, forwards',
          }}
        />
      )}

      {/* ── Entry buttons ──────────────────────────────────────────────────── */}
      {/*
       * Pre-allocated height (opacity, not conditional) prevents CLS:
       * the button row occupies layout space from the start; only its
       * visibility changes when done flips true.
       *
       * Rise animation fires only after the AVIF flipbook completes.
       * Static paths (reduced-motion, no AVIF) skip the rise — buttons
       * appear immediately without animation, matching reduced-motion intent.
       */}
      <div
        className="flex gap-5 mt-8"
        style={{
          opacity:       done ? undefined : 0,
          pointerEvents: done ? 'auto' : 'none',
          animation:     (done && !showStatic) ? 'mw-rise 0.3s ease-out forwards' : undefined,
        }}
      >
        <Link
          href="/boys"
          className={[
            'flex items-center justify-center gap-2',
            'w-36 py-3',
            'bg-blue-600 text-white font-bold text-lg',
            'border-2 border-blue-600',
            'rounded-none',
            'hover:bg-blue-700 hover:border-blue-700',
            'transition-colors',
            'focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 focus-visible:ring-offset-2',
          ].join(' ')}
        >
          Boys
          <span aria-hidden="true">→</span>
        </Link>

        <Link
          href="/girls"
          className={[
            'flex items-center justify-center gap-2',
            'w-36 py-3',
            'bg-rose-800 text-white font-bold text-lg',
            'border-2 border-rose-800',
            'rounded-none',
            'hover:bg-rose-900 hover:border-rose-900',
            'transition-colors',
            'focus:outline-none focus-visible:ring-2 focus-visible:ring-rose-800 focus-visible:ring-offset-2',
          ].join(' ')}
        >
          Girls
          <span aria-hidden="true">→</span>
        </Link>
      </div>
    </section>
  )
}
